import {
  Box,
  Container,
  Heading,
  HStack,
  Text,
  VStack,
  Input,
  InputLeftElement,
  InputGroup,
  Icon,
} from "@chakra-ui/react";
import Head from "next/head";

import {FaSearch} from "react-icons/fa";

import ItemCard from "../components/ItemCard/ItemCard";

export default function Items({mainState}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Container maxW={"100%"}>
        <Text as={"b"} fontSize="4xl">
          Welcome to schoolx
        </Text>
      </Container>
    </div>
  );
}
